accountapp/urls.py
from django.urls import path
from .views import AccountCreateView, AccountDetailView, AccountUpdateView,AccountDeleteView
from django.contrib.auth.views import LoginView, LogoutView

app_name = "accountapp"

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
    
]

pragmatic/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profile/', include('profileapp.urls')),
]

profileapp/urls.py
from django.urls import path
from profileapp.views import ProfileCreateView

app_name = "profileapp"

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),    
]

accountapp/models.py
from django.db import models

# Create your models here.

profileapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    image = models.ImageField(default='default.jpg', upload_to='profile_pics', null=True, blank=True)
    nickname = models.CharField(max_length=20, unique=True, null=True)
    message = models.CharField(max_length=100, null=True)

    

profileapp/forms.py
from django.forms import ModelForm
from .models import *

class ProfileCreationForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['image','nickname', 'message']

accountapp/views.py
from django.shortcuts import render
from django.views.generic import CreateView, DetailView, UpdateView,DeleteView
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from accountapp.form import AccountUpdateForm
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from accountapp.decorators import account_ownership_required

# Create your views here.
has_ownership = [account_ownership_required, login_required]


class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('accountapp:login')
    template_name = 'accountapp/create.html'


class AccountDetailView(DetailView):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountapp/detail.html'

@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountUpdateView(UpdateView):
    model = User
    context_object_name = 'target_user'
    fields = ['username', 'email'] 

    format_class = AccountUpdateForm
    success_url = reverse_lazy('accountapp:login')
    template_name = 'accountapp/update.html'

@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:login')
    template_name = 'accountapp/delete.html'

profileapp/views.py
from .models import Profile
from .forms import ProfileCreationForm
from django.views.generic import CreateView
from django.urls import reverse_lazy


# Create your views here.
class ProfileCreateView(CreateView):
    model = Profile
    context_oject_name = 'targer_profile'    
    form_class = ProfileCreationForm
    succes_url = reverse_lazy('accountapp:login')
    template_name = 'profileapp/create.html'

    def form_valid(self, form):
        temp_profile = form.save(commit=False)
        temp_profile.user = self.request.user
        temp_profile.save()
        return super().form_valid(form)

accountapp/templates/accountapp/create.html
{% block content %}
<form action="{% url "accountapp:create" %}" method="POST">
    {{csf_token}}
    {{form}}
    <input type="submit">
</form>

{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends "base.html" %} {% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <h1>Quit</h1>
    </div>
    <div class="col-md-4">
      <form action="{% url "accountapp:delete" pk=target_user.pk %}"
      method="post">
      <div class="form-group">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Quit" />
      </div>
    </div>
  </div>
  {% endblock %}
</div>

accountapp/templates/accountapp/detail.html
{% extends "base.html" %} {% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>{{ target_user.date_joined }}</h1>
      {% if target_user.profile %}
      <p>{{ target_user.profile.nickname }}</p>
      {% else %}
      <p>
        <a href="{% url 'profileapp:create' %}">Edit Profile</a>
      </p>
      {% endif %} {% if target_user == user %}
      <p>
        <a href="{% url 'accountapp:delete' pk=target_user.pk %}">delete</a>
      </p>
      {% endif %}
      <hr />
    </div>
  </div>
</div>

{% endblock %}

accountapp/templates/accountapp/login.html
{% extends "base.html" %} {% load bootstrap4 %} {% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
      <div class="card card-signin my-5">
        <div class="card-body">
          <h5 class="card-title text-center">Login</h5>
          <form
            class="form-signin"
            action="{% url 'accountapp:login' %}"
            method="post"
          >
            {% csrf_token %} {% bootstrap_form form %} {% buttons %}
            <button
              type="submit"
              class="btn btn-primary btn-block text-uppercase"
            >
              Login
            </button>
            {% endbuttons %}
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

accountapp/templates/accountapp/update.html
{% extends "base.html" %}


{% block content %}
<h1>Update Account</h1>
<form action="{% url "accountapp:update" pk=target_user.pk %}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>



{% endblock %}

profileapp/templates/profileapp/create.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}
<form action="{% url "profileapp:create" %}" method="POST" >
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit">
</form>

{% endblock %}

templates/base.html
<!<!DOCTYPE html>
<html lang="en">
  {% include 'head.html' %}
  <body>
    {% include "header.html" %}
    <hr />
    {% block content %} {% endblock %}
    <hr />
    {% include "footer.html" %}
  </body>
</html>

templates/footer.html
<div sytle="text-align:center;">
  <div>
    <span>nav1</span> | <span>nav2</span> | <span>nav3</span> |
    <span>nav4</span>
  </div>
  <div>
    <h6></h6>
  </div>
</div>

templates/head.html
{% load static %}

<head>
  <meta charset="UTF-8" />
  <title>Document</title>
  <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
    crossorigin="anonymous"
  />
  <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"
  ></script>

  <link rel="stylesheet" href="{% static 'css/style.css' %}" />
</head>

templates/header.html
<div sytle="text-align:center;">
  <div><h1>Welcome to My Website</h1></div>
  <div>
    <span>nav1</span> | <span>nav2</span> | <span>nav3</span>

    {% if user.is_authenticated %}
    <a href="{% url 'accountapp:detail' user.pk %}">
      <span>Mypage</span>
    </a>
    <a href="{% url 'accountapp:logout' %}?next={{ request.path }}">
      <span>Logout</span>
    </a>
    {% else %}
    <a href="{% url 'accountapp:login' %}?next={{ request.path }}">
      <span>Login</span>
    </a>
    <a href="{% url 'accountapp:create' %}?next={{ request.path }}">
      <span>Sign-up</span>
    </a>
    {% endif %}
  </div>
</div>